# Generated by Django 5.0.7 on 2024-08-29 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='article_art_created_d3bafd_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at', 'id'], name='article_art_created_4eeae0_idx'),
        ),
    ]
