# Generated by Django 5.0.7 on 2024-07-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articleuserrelations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuserrelations',
            name='in_bookmarks',
            field=models.BooleanField(default=False),
        ),
    ]
