# Generated by Django 5.0.7 on 2024-07-31 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_articleuserrelations_in_bookmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='readers',
            field=models.ManyToManyField(related_name='readers', through='article.ArticleUserRelations', to=settings.AUTH_USER_MODEL),
        ),
    ]
