# Generated by Django 5.0.7 on 2024-07-31 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_readers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_article', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='article',
            name='readers',
            field=models.ManyToManyField(related_name='readers_article', through='article.ArticleUserRelations', to=settings.AUTH_USER_MODEL),
        ),
    ]
