# Generated by Django 5.0.7 on 2024-08-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_articleuserrelations_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuserrelations',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=False, null=True),
        ),
    ]
