# Generated by Django 5.0.7 on 2024-08-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_tag_tagarticlerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tagged_by',
            field=models.ManyToManyField(related_name='articles', to='article.tag'),
        ),
    ]
