# Generated by Django 5.0.7 on 2024-08-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_alter_article_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tagged_by',
            field=models.ManyToManyField(blank=True, related_name='articles', to='article.tag'),
        ),
    ]
