# Generated by Django 5.0.7 on 2024-08-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_alter_article_tagged_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuserrelations',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=None, null=True),
        ),
    ]
